// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Evently.Modules.Users.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Update_Outbox_and_Inbox : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "users"."inbox_messages" 
                ALTER COLUMN "content" TYPE jsonb 
                USING "content"::jsonb;
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE "users"."outbox_messages" 
                ALTER COLUMN "content" TYPE jsonb 
                USING "content"::jsonb;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "users"."inbox_messages" 
                ALTER COLUMN "content" TYPE character varying(2000) 
                USING "content"::text;
                """);

            migrationBuilder.Sql(
                """
                ALTER TABLE "users"."outbox_messages" 
                ALTER COLUMN "content" TYPE character varying(2000) 
                USING "content"::text;
                """);
        }
    }
}
